/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"

#if !defined(__SOFT_6FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	LedInit(GPIO_GREEN);
	LedInit(GPIO_ORANGE);
	LedInit(GPIO_RED);
	LedInit(GPIO_BLUE);

	while(1){
		LedOn(GPIO_GREEN);

		LedOn(GPIO_ORANGE);
		DelayMs(200);
		LedOff(GPIO_ORANGE);

		LedOn(GPIO_RED);

		LedOn(GPIO_BLUE);
		DelayMs(200);
		LedOff(GPIO_BLUE);

		LedOn(GPIO_ORANGE);
	}

	return 0;
}
